sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx15bbe5913b3a236f
    secret: 8de4bb72ad9c137f805e8a22371e3d2a

  aliyun:
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      bucket-name: web-tlias-hyx2002